/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EAUDIOFOCUS_AUTODEFS_H
#define S3EAUDIOFOCUS_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_AUDIOFOCUS_NAME "s3eAudioFocus"
#define S3E_EXT_AUDIOFOCUS_HASH 0x1e576102

#ifdef S3E_EXT_REGISTER
#ifndef S3E_EXT_REGISTER_KEY
#define S3E_EXT_REGISTER_KEY(name, num, key) S3E_EXT_REGISTER(name, num)
#endif
S3E_EXT_REGISTER("s3eAudioFocus", 1)
S3E_EXT_REGISTER("s3eAudioFocus", 1)
#else

#endif /* S3E_EXT_REGISTER */
#endif /* !S3EAUDIOFOCUS_AUTODEFS_H */
