/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/*
 * This file contains the automatically generated loader-side
 * functions that form part of the extension.
 *
 * This file is awlays compiled into all loaders but compiles
 * to nothing if this extension is not enabled in the loader
 * at build time.
 */
#include "s3eAudioFocus_autodefs.h"
#include "s3eEdk.h"
#include "s3eAudioFocus.h"
//Declarations of Init and Term functions
extern s3eResult s3eAudioFocusInit();
extern void s3eAudioFocusTerminate();


void s3eAudioFocusRegisterExt()
{
    /* fill in the function pointer struct for this extension */
    void* funcPtrs[1];
    funcPtrs[0] = (void*)s3eAudioFocusRequestFocuse;

    /*
     * Flags that specify the extension's use of locking and stackswitching
     */
    int flags[1] = { 0 };

    /*
     * Register the extension
     */
s3eEdkRegister("s3eAudioFocus", funcPtrs, sizeof(funcPtrs), flags, s3eAudioFocusInit, s3eAudioFocusTerminate, 0);
    /*
     * Register the extension using alternative name
     */
s3eEdkRegister("s3eAudioFocus", funcPtrs, sizeof(funcPtrs), flags, s3eAudioFocusInit, s3eAudioFocusTerminate, 0);
}

#if !defined S3E_BUILD_S3ELOADER

#if defined S3E_EDK_USE_STATIC_INIT_ARRAY
int s3eAudioFocusStaticInit()
{
    void** p = g_StaticInitArray;
    void* end = p + g_StaticArrayLen;
    while (*p) p++;
    if (p < end)
        *p = (void*)&s3eAudioFocusRegisterExt;
    return 0;
}

int g_s3eAudioFocusVal = s3eAudioFocusStaticInit();

#elif defined S3E_EDK_USE_DLLS
S3E_EXTERN_C S3E_DLL_EXPORT void RegisterExt()
{
    s3eAudioFocusRegisterExt();
}
#endif

#endif
